### ISSUE TITLE
Exception handling model

### ISSUE THREAD

**Issue by wangzhankun** [jxy-s/stlkrn#11]
Here is the msvc [Exception handling model](https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170). So what option should I use when integrating your stl code ？

**Comment by jxy-s** [comment]
`vcrtl` applies the following:

https://github.com/jxy-s/stlkrn/blob/main/third-party/vcrtl/vcrtl_driver.props#L10

I have not tested with other models, your mileage may vary.
