### ISSUE TITLE
Memory leak inside thread class

### ISSUE THREAD

**Issue by lucianpin** [jxy-s/stlkrn#12]
https://github.com/jxy-s/stlkrn/blob/cee8fe7825c2c8e88b689a2152140bc5ac12a492/include/jxy/thread.hpp#L94

Destructor of 'funcVals' is not called because PsTerminateSystemThread does not return if it successfully terminates the calling thread (according to MSDN) and thus would result a memory leak.

Solution would be that lines 94-96 to be inside a new separate scope.

**Comment by jxy-s** [comment]
👍 fixed with https://github.com/jxy-s/stlkrn/commit/e4de9c4ababaa69416559db1525d21ca0b8f1abb
