### ISSUE TITLE
C++17 compilation error

### ISSUE THREAD

**Issue by lwl4613615** [jxy-s/stlkrn#14]
I encountered this problem when I used the latest version of VS2022 and the latest WDK to compile C++17.
include\jxy\memory.hpp(147,21): error C3861: “_Voidify_iter”: identifier not found.

**Comment by jxy-s** [comment]
should be fixed with https://github.com/jxy-s/stlkrn/commit/26af6fc495bb9ee322b8e0ae206a39004a5a7086 👍
