### ISSUE TITLE
span

### ISSUE THREAD

**Issue by ddkwork** [jxy-s/stlkrn#15]
where std span?

**Comment by jxy-s** [comment]
`std::span` doesn't require an allocator, so there is no need to wrap it. You can just include it, here is an example of atomic being included:
https://github.com/jxy-s/stlkrn/blob/26af6fc495bb9ee322b8e0ae206a39004a5a7086/stlkrn/thread_context.hpp#L14

An aside: for atomic there is a problem with the emitted instructions for 32bit that isn't patched for the kernel. Should work fine on 64bit.
